//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Balance = 0m;
            this.WalletTransactions = new HashSet<WalletTransaction>();
        }
    
        public long ID { get; set; }
        public string UserID { get; set; }
        public decimal Balance { get; set; }
        public int AccountStateId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
    
        public virtual ICollection<WalletTransaction> WalletTransactions { get; set; }
        public virtual AccountState AccountState { get; set; }
    }
}
