//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WalletService
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletTransaction
    {
        public WalletTransaction()
        {
            this.Amount = 0m;
        }
    
        public long TransactionID { get; set; }
        public long AccountID { get; set; }
        public int TransactionTypeId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
